### ISSUE TITLE
Colab demo

### ISSUE THREAD

**Issue by msharmavikram** [lynnliu030/LLM-SQL-Demo#10]
Please add the colab demo to the repo. We cannot capture the link so quickly during the discussion at retreat.

**Comment by amogkam** [comment]
Colab demo is here :) https://colab.research.google.com/drive/1kTe1JukxUJi93cSD6yyU3s5ZhF6ezD2S?usp=sharing

**Comment by amogkam** [comment]
The notebook is also in the `examples` directory (https://github.com/lynnliu030/LLM-SQL-Demo/blob/main/examples/duckdb/movies_example_colab.ipynb)
